id: P000463
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:41:15.188407
source_metadata:
  id: bdr:W8LS19449
  title: དངོས་གཞིའི་ཟིན་བྲིས་བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མེ།
  author: ''
  volumes:
    fee5fcdf5f654280bcb2b74f01b81ec5:
      image_group_id: I8LS19451
      title: Volume 1 of dngos gzhi'i zin bris byang chub lam gyi sgron me/
      volume_number: 1
      total_pages: 104
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
